# Generated by Django 5.2.5 on 2026-07-20 12:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price')),
                ('delivery_time_days', models.PositiveIntegerField(default=1, verbose_name='Delivery Time (days)')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Design Option',
                'verbose_name_plural': 'Design Options',
            },
        ),
        migrations.CreateModel(
            name='DesignPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('delivery_time_days', models.PositiveIntegerField(default=7, verbose_name='Delivery Time (days)')),
                ('price_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Price Multiplier')),
                ('services_after_payment', models.TextField(blank=True, verbose_name='Services After Payment')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Design Package',
                'verbose_name_plural': 'Design Packages',
            },
        ),
        migrations.CreateModel(
            name='InspirationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='inspirations/', verbose_name='Image')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Title')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Inspiration Image',
                'verbose_name_plural': 'Inspiration Images',
            },
        ),
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=19.0, max_digits=5, verbose_name='Tax Rate (%)')),
                ('default_revision_count', models.PositiveIntegerField(default=2, verbose_name='Default Revision Count')),
                ('currency_symbol', models.CharField(default='DA', max_length=10, verbose_name='Currency Symbol')),
                ('default_delivery_days', models.PositiveIntegerField(default=30, verbose_name='Default Delivery Days')),
            ],
            options={
                'verbose_name': 'Pricing Configuration',
                'verbose_name_plural': 'Pricing Configuration',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('image', models.ImageField(blank=True, null=True, upload_to='marketplace/products/', verbose_name='Image')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='SKU')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='marketplace/categories/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
            },
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='project_types/', verbose_name='Image')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('sort_order', models.IntegerField(default=0, unique=True, verbose_name='Sort Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Project Type',
                'verbose_name_plural': 'Project Types',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Service Category',
                'verbose_name_plural': 'Service Categories',
            },
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('image', models.ImageField(blank=True, null=True, upload_to='spaces/', verbose_name='Image')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Category')),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Base Price')),
                ('estimated_days', models.PositiveIntegerField(default=1, verbose_name='Estimated Days')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Space',
                'verbose_name_plural': 'Spaces',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SpaceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Space Category',
                'verbose_name_plural': 'Space Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StyleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Style Category',
                'verbose_name_plural': 'Style Categories',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
            },
        ),
        migrations.CreateModel(
            name='DesignRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('project_name', models.CharField(max_length=200, verbose_name='Project Name')),
                ('status', models.CharField(choices=[('new', 'New'), ('qualified', 'Qualified'), ('quote_sent', 'Quote Sent'), ('waiting_payment', 'Waiting Payment'), ('design', 'Design'), ('revision', 'Revision'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='new', max_length=20, verbose_name='Status')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Budget')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Delivery Date')),
                ('revision_count', models.PositiveIntegerField(default=2, verbose_name='Revision Count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_requests', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('designer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL, verbose_name='Designer')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='dashboard.designpackage', verbose_name='Package')),
                ('project_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='dashboard.projecttype', verbose_name='Project Type')),
            ],
            options={
                'verbose_name': 'Design Request',
                'verbose_name_plural': 'Design Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DesignPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('payment_method', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('manual', 'Manual Transfer')], max_length=20, verbose_name='Payment Method')),
                ('transaction_id', models.CharField(blank=True, max_length=200, verbose_name='Transaction ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='Status')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Paid At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('design_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='dashboard.designrequest', verbose_name='Design Request')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='DesignNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(verbose_name='Note')),
                ('is_internal', models.BooleanField(default=True, verbose_name='Is Internal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_notes', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('design_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='dashboard.designrequest', verbose_name='Design Request')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DesignMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='design-requests/messages/', verbose_name='Attachment')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_messages', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
                ('design_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='dashboard.designrequest', verbose_name='Design Request')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DesignDeliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('file', models.FileField(upload_to='design-requests/deliverables/', verbose_name='File')),
                ('file_type', models.CharField(blank=True, max_length=50, verbose_name='File Type')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_deliverables', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
                ('design_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='dashboard.designrequest', verbose_name='Design Request')),
            ],
            options={
                'verbose_name': 'Deliverable',
                'verbose_name_plural': 'Deliverables',
                'ordering': ['design_request', '-version'],
            },
        ),
        migrations.CreateModel(
            name='DesignActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='Action')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_activities', to=settings.AUTH_USER_MODEL, verbose_name='Actor')),
                ('design_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='dashboard.designrequest', verbose_name='Design Request')),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DesignRequestFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='design-requests/files/', verbose_name='File')),
                ('file_type', models.CharField(blank=True, max_length=50, verbose_name='File Type')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('design_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='dashboard.designrequest', verbose_name='Design Request')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Request File',
                'verbose_name_plural': 'Request Files',
            },
        ),
        migrations.CreateModel(
            name='DesignRequestFloor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('level', models.IntegerField(default=0, verbose_name='Level')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('design_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='dashboard.designrequest', verbose_name='Design Request')),
            ],
            options={
                'verbose_name': 'Floor',
                'verbose_name_plural': 'Floors',
                'ordering': ['design_request', 'order'],
            },
        ),
        migrations.CreateModel(
            name='DesignRequestOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_at_time', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price at Time')),
                ('design_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='dashboard.designrequest', verbose_name='Design Request')),
                ('option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_options', to='dashboard.designoption', verbose_name='Option')),
            ],
            options={
                'verbose_name': 'Request Option',
                'verbose_name_plural': 'Request Options',
            },
        ),
        migrations.CreateModel(
            name='DesignRequestSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_name', models.CharField(blank=True, max_length=200, verbose_name='Custom Name')),
                ('price_at_time', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price at Time')),
                ('design_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='dashboard.designrequest', verbose_name='Design Request')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='dashboard.designrequestfloor', verbose_name='Floor')),
                ('space', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_spaces', to='dashboard.space', verbose_name='Space')),
            ],
            options={
                'verbose_name': 'Request Space',
                'verbose_name_plural': 'Request Spaces',
            },
        ),
        migrations.CreateModel(
            name='DesignRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.PositiveIntegerField(verbose_name='Revision Number')),
                ('reason', models.TextField(verbose_name='Reason')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('design_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='dashboard.designrequest', verbose_name='Design Request')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_revisions', to=settings.AUTH_USER_MODEL, verbose_name='Requested By')),
            ],
            options={
                'verbose_name': 'Revision',
                'verbose_name_plural': 'Revisions',
                'ordering': ['design_request', '-revision_number'],
            },
        ),
        migrations.CreateModel(
            name='DesignRequestInspiration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_request_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspirations', to='dashboard.designrequestspace', verbose_name='Request Space')),
                ('inspiration_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_inspirations', to='dashboard.inspirationimage', verbose_name='Inspiration Image')),
            ],
            options={
                'verbose_name': 'Request Inspiration',
                'verbose_name_plural': 'Request Inspirations',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('notification_type', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=20, verbose_name='Notification Type')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('link', models.CharField(blank=True, help_text='Optional navigation link', max_length=500, verbose_name='Link')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='Payment Method')),
                ('shipping_address', models.TextField(blank=True, verbose_name='Shipping Address')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_orders', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackageService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Sort Order')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_services', to='dashboard.designoption', verbose_name='Service')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_services', to='dashboard.designpackage', verbose_name='Package')),
            ],
            options={
                'verbose_name': 'Package Service',
                'verbose_name_plural': 'Package Services',
                'ordering': ['sort_order'],
                'unique_together': {('package', 'option')},
            },
        ),
        migrations.AddField(
            model_name='designpackage',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='packages', through='dashboard.PackageService', to='dashboard.designoption', verbose_name='Services'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('price_at_time', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price at Time')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dashboard.order', verbose_name='Order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='dashboard.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('price_at_time', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price at Time')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dashboard.cart', verbose_name='Cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='dashboard.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Cart Item',
                'verbose_name_plural': 'Cart Items',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='dashboard.productcategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='designoption',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_options', to='dashboard.servicecategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='inspirationimage',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspiration_images', to='dashboard.space', verbose_name='Space'),
        ),
        migrations.AddField(
            model_name='space',
            name='space_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spaces', to='dashboard.spacecategory', verbose_name='Space Category'),
        ),
        migrations.AddField(
            model_name='inspirationimage',
            name='style_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspiration_images', to='dashboard.stylecategory', verbose_name='Style Category'),
        ),
        migrations.CreateModel(
            name='ProjectTypeSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Sort Order')),
                ('project_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_spaces', to='dashboard.projecttype', verbose_name='Project Type')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_types', to='dashboard.space', verbose_name='Space')),
            ],
            options={
                'verbose_name': 'Default Space for Type',
                'verbose_name_plural': 'Default Spaces for Types',
                'ordering': ['project_type', 'sort_order'],
                'unique_together': {('project_type', 'space')},
            },
        ),
        migrations.CreateModel(
            name='SpaceProductRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField(default=0, verbose_name='Priority')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_recommendations', to='dashboard.product', verbose_name='Product')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_recommendations', to='dashboard.space', verbose_name='Space')),
            ],
            options={
                'verbose_name': 'Product Recommendation',
                'verbose_name_plural': 'Product Recommendations',
                'ordering': ['space', 'priority'],
                'unique_together': {('space', 'product')},
            },
        ),
    ]
