# Generated by Django 5.2.5 on 2026-07-20 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_inquiry_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspirationimage',
            name='style_category',
        ),
    ]
