# Generated by Django 6.0.7 on 2026-07-30 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_designrequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('thumbnail', models.ImageField(upload_to='portfolio/thumbnails/', verbose_name='Thumbnail')),
                ('description', models.TextField(verbose_name='Description')),
                ('tags', models.CharField(help_text='Comma separated tags', max_length=10000, verbose_name='Tags')),
                ('external_link', models.URLField(blank=True, null=True, verbose_name='External Link')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Is Featured')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/gallery/', verbose_name='Image')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='dashboard.portfolio', verbose_name='Portfolio')),
            ],
            options={
                'verbose_name': 'Portfolio Image',
                'verbose_name_plural': 'Portfolio Images',
            },
        ),
    ]
