# Generated by Django 5.2.5 on 2026-07-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_portfolio_portfoliogallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='tags',
            field=models.CharField(help_text='Comma separated tags', max_length=100000, verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='title',
            field=models.CharField(max_length=1000, verbose_name='Title'),
        ),
    ]
