# Generated by Django 6.0.7 on 2026-07-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_portfolio_tags_alter_portfolio_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='model_3d',
            field=models.FileField(blank=True, help_text='Upload a GLB/GLTF 3D model', null=True, upload_to='portfolio/models/', verbose_name='3D Model'),
        ),
    ]
