# Generated by Django 6.0.7 on 2026-07-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_portfolio_model_3d'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma separated tags', max_length=100000, verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/thumbnails/', verbose_name='Thumbnail'),
        ),
    ]
