# Generated by Django 6.0.7 on 2026-07-31 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_portfolio_tags_alter_portfolio_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='space_category',
        ),
        migrations.AlterModelOptions(
            name='projecttype',
            options={'ordering': ['name'], 'verbose_name': 'Project Type', 'verbose_name_plural': 'Project Types'},
        ),
        migrations.RemoveField(
            model_name='projecttype',
            name='active',
        ),
        migrations.RemoveField(
            model_name='projecttype',
            name='description',
        ),
        migrations.RemoveField(
            model_name='projecttype',
            name='image',
        ),
        migrations.RemoveField(
            model_name='projecttype',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='space',
            name='active',
        ),
        migrations.RemoveField(
            model_name='space',
            name='category',
        ),
        migrations.RemoveField(
            model_name='space',
            name='image',
        ),
        migrations.CreateModel(
            name='SpaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='spaces/gallery/', verbose_name='Image')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='dashboard.space', verbose_name='Space')),
            ],
            options={
                'verbose_name': 'Space Image',
                'verbose_name_plural': 'Space Images',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='SpaceCategory',
        ),
    ]
