# Generated by Django 6.0.7 on 2026-07-31 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_remove_space_space_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spaceimage',
            name='is_thumbnail',
            field=models.BooleanField(default=False, verbose_name='Is Thumbnail'),
        ),
    ]
