# Generated by Django 6.0.7 on 2026-07-31 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_spaceimage_is_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='visible_in_request',
            field=models.BooleanField(default=True, verbose_name='Visible in Request'),
        ),
    ]
