# Generated by Django 6.0.7 on 2026-07-31 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_space_visible_in_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='visible_in_request',
        ),
    ]
