# Generated by Django 6.0.7 on 2026-08-01 09:22

from django.db import migrations, models


def ensure_others_type_and_dedupe(apps, schema_editor):
    ProjectType = apps.get_model("dashboard", "ProjectType")
    ProjectTypeSpace = apps.get_model("dashboard", "ProjectTypeSpace")

    other, _ = ProjectType.objects.get_or_create(
        slug="others", defaults={"name": "Others"},
    )

    space_ids = (
        ProjectTypeSpace.objects.values_list("space_id", flat=True)
        .distinct()
    )
    for space_id in space_ids:
        links = list(ProjectTypeSpace.objects.filter(space_id=space_id).order_by("id"))
        if len(links) <= 1:
            continue
        keep = next(
            (link for link in links if link.project_type_id != other.pk),
            links[0],
        )
        ProjectTypeSpace.objects.filter(space_id=space_id).exclude(pk=keep.pk).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_remove_space_visible_in_request'),
    ]

    operations = [
        migrations.RunPython(ensure_others_type_and_dedupe, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='projecttypespace',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='projecttypespace',
            constraint=models.UniqueConstraint(fields=('space',), name='unique_space_project_type'),
        ),
    ]
