# Generated by Django 6.0.7 on 2026-08-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_remove_others_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttype',
            name='featured_on_home',
            field=models.BooleanField(default=False, verbose_name='Featured on Home'),
        ),
        migrations.AddField(
            model_name='projecttypespace',
            name='show_on_home',
            field=models.BooleanField(default=False, verbose_name='Show on Home'),
        ),
    ]
