# Generated by Django 6.0.7 on 2026-08-03 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_projecttype_featured_on_home_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignRequestSpaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_request_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_images', to='dashboard.designrequestspace', verbose_name='Request Space')),
                ('space_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_space_images', to='dashboard.spaceimage', verbose_name='Gallery Image')),
            ],
            options={
                'verbose_name': 'Request Gallery Image',
                'verbose_name_plural': 'Request Gallery Images',
            },
        ),
        migrations.RemoveField(
            model_name='designrequestinspiration',
            name='design_request_space',
        ),
        migrations.RemoveField(
            model_name='designrequestinspiration',
            name='inspiration_image',
        ),
        migrations.RemoveField(
            model_name='inspirationimage',
            name='space',
        ),
        migrations.DeleteModel(
            name='StyleCategory',
        ),
        migrations.DeleteModel(
            name='DesignRequestInspiration',
        ),
        migrations.DeleteModel(
            name='InspirationImage',
        ),
    ]
