# Generated by Django 5.2.5 on 2026-08-05 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_remove_space_estimated_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designoption',
            name='delivery_time_days',
        ),
        migrations.RemoveField(
            model_name='designoption',
            name='price',
        ),
    ]
