# Generated by Django 5.2.5 on 2026-08-07 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_remove_designoption_delivery_time_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designpackage',
            name='active',
        ),
        migrations.RemoveField(
            model_name='designpackage',
            name='description',
        ),
    ]
