# Generated by Django 5.2.5 on 2026-08-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_remove_designpackage_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='inspirations',
            field=models.JSONField(blank=True, default=dict, verbose_name='Inspirations'),
        ),
    ]
