# Generated by Django 5.2.5 on 2026-08-10 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_spaceimage_unique_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='designpackage',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Default Package'),
        ),
    ]
