# Generated by Django 5.2.5 on 2026-08-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_designpackage_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='designpackage',
            name='link',
            field=models.URLField(blank=True, verbose_name='Video Link'),
        ),
    ]
