# Generated by Django 5.2.5 on 2026-08-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_contact_lead_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='spaceimage',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='spaceimage',
            name='reference',
            field=models.CharField(blank=True, default='', editable=False, max_length=500, verbose_name='Reference'),
        ),
        migrations.AddField(
            model_name='spaceimage',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Tags (comma-separated)'),
        ),
    ]
