# Generated by Django 5.2.5 on 2026-08-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_spaceimage_description_spaceimage_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spaceimage',
            name='reference',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Reference'),
        ),
        migrations.AlterField(
            model_name='spaceimage',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Tags'),
        ),
    ]
