# Generated by Django 5.2.5 on 2026-08-17 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=150, verbose_name='Service Name')),
                ('service_price', models.IntegerField(default=0, verbose_name='Service Price (DA)')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is Default')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['service_name'],
            },
        ),
        migrations.RemoveField(
            model_name='designoption',
            name='category',
        ),
        migrations.RemoveField(
            model_name='designrequestoption',
            name='option',
        ),
        migrations.AlterUniqueTogether(
            name='packageservice',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='packageservice',
            name='option',
        ),
        migrations.RemoveField(
            model_name='packageservice',
            name='package',
        ),
        migrations.RemoveField(
            model_name='designrequest',
            name='package',
        ),
        migrations.RemoveConstraint(
            model_name='spaceimage',
            name='unique_space_image_content_hash',
        ),
        migrations.RemoveField(
            model_name='spaceimage',
            name='space',
        ),
        migrations.AddField(
            model_name='designrequest',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='dashboard.service', verbose_name='Service'),
        ),
        migrations.AddField(
            model_name='designrequestoption',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_options', to='dashboard.service', verbose_name='Service'),
        ),
        migrations.CreateModel(
            name='SpaceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=150, verbose_name='Category Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='dashboard.space', verbose_name='Space')),
            ],
            options={
                'verbose_name': 'Space Category',
                'verbose_name_plural': 'Space Categories',
                'ordering': ['category_name'],
            },
        ),
        migrations.CreateModel(
            name='SpaceCategoryImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='spaces/gallery/', verbose_name='Image')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is Default')),
                ('content_hash', models.CharField(blank=True, default='', editable=False, max_length=64, verbose_name='Content Hash')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('tags', models.CharField(blank=True, default='', max_length=500, verbose_name='Tags')),
                ('reference', models.CharField(blank=True, default='', max_length=500, verbose_name='Reference')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dashboard.spacecategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Space Category Image',
                'verbose_name_plural': 'Space Category Images',
                'ordering': ['-is_default', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='designrequestspaceimage',
            name='space_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_space_images', to='dashboard.spacecategoryimages', verbose_name='Gallery Image'),
        ),
        migrations.DeleteModel(
            name='ServiceCategory',
        ),
        migrations.DeleteModel(
            name='DesignOption',
        ),
        migrations.DeleteModel(
            name='DesignPackage',
        ),
        migrations.DeleteModel(
            name='PackageService',
        ),
        migrations.AddConstraint(
            model_name='spacecategoryimages',
            constraint=models.UniqueConstraint(condition=models.Q(('content_hash', ''), _negated=True), fields=('category', 'content_hash'), name='unique_space_cat_image_content_hash'),
        ),
        migrations.DeleteModel(
            name='SpaceImage',
        ),
    ]
