# Generated by Django 5.2.5 on 2026-08-17 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_service_remove_designoption_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='ServicePricing',
        ),
        migrations.AlterModelOptions(
            name='servicepricing',
            options={
                'ordering': ['service_name'],
                'verbose_name': 'Service Pricing',
                'verbose_name_plural': 'Service Pricings',
            },
        ),
        migrations.AddField(
            model_name='servicepricing',
            name='pricing_type',
            field=models.CharField(choices=[('fixed', 'Fixed Price'), ('area', 'Price per Square Metre (m²)'), ('hourly', 'Price per Hour')], default='fixed', max_length=20, verbose_name='Pricing Type'),
        ),
        migrations.AddField(
            model_name='servicepricing',
            name='video_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Video Link'),
        ),
        migrations.AddField(
            model_name='servicepricing',
            name='gif_file',
            field=models.FileField(blank=True, null=True, upload_to='services/gifs/', verbose_name='GIF / Preview File'),
        ),
        migrations.AlterField(
            model_name='servicepricing',
            name='service_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Price (DA)'),
        ),
        migrations.AddField(
            model_name='designrequest',
            name='floors_above',
            field=models.IntegerField(default=0, verbose_name='Floors Above RDC'),
        ),
        migrations.AddField(
            model_name='designrequest',
            name='floors_below',
            field=models.IntegerField(default=0, verbose_name='Floors Below RDC'),
        ),
        migrations.AddField(
            model_name='designrequest',
            name='has_terrace',
            field=models.BooleanField(default=False, verbose_name='Has Terrace'),
        ),
        migrations.AddField(
            model_name='designrequest',
            name='total_surface',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Surface (m²)'),
        ),
        migrations.AddField(
            model_name='designrequestfloor',
            name='surface',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Surface (m²)'),
        ),
    ]
