# Generated by Django 5.2.5 on 2026-08-18 00:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_servicepricing_designrequest_floors_above_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectGalleryInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token')),
                ('email', models.EmailField(max_length=254, verbose_name='Recipient Email')),
                ('is_used', models.BooleanField(default=False, verbose_name='Is Used')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Used At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('design_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_invitations', to='dashboard.designrequest', verbose_name='Design Request')),
            ],
            options={
                'verbose_name': 'Project Gallery Invitation',
                'verbose_name_plural': 'Project Gallery Invitations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DesignRequestGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Client Notes')),
                ('selected_at', models.DateTimeField(auto_now_add=True, verbose_name='Selected At')),
                ('design_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_selections', to='dashboard.designrequest', verbose_name='Design Request')),
                ('space_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_gallery_selections', to='dashboard.spacecategoryimages', verbose_name='Gallery Image')),
            ],
            options={
                'verbose_name': 'Design Request Gallery Selection',
                'verbose_name_plural': 'Design Request Gallery Selections',
                'ordering': ['selected_at'],
                'constraints': [models.UniqueConstraint(fields=('design_request', 'space_image'), name='unique_request_gallery_image')],
            },
        ),
    ]
