# Generated by Django 5.2.5 on 2026-08-18 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_projectgalleryinvitation_designrequestgalleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='designrequest',
            name='has_garden',
            field=models.BooleanField(default=False, verbose_name='Has Garden'),
        ),
    ]
