# Generated by Django 6.0.7 on 2026-08-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_designrequest_has_garden'),
    ]

    operations = [
        migrations.AddField(
            model_name='designrequest',
            name='client_type',
            field=models.CharField(choices=[('particular', 'Particulier'), ('professional', 'Professionnel')], default='particular', max_length=20, verbose_name='Client Type'),
        ),
        migrations.AddField(
            model_name='designrequest',
            name='commune',
            field=models.CharField(blank=True, max_length=100, verbose_name='Commune'),
        ),
        migrations.AddField(
            model_name='designrequest',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Company Name'),
        ),
        migrations.AddField(
            model_name='designrequest',
            name='message',
            field=models.TextField(blank=True, verbose_name='Message / Notes'),
        ),
        migrations.AddField(
            model_name='designrequest',
            name='mode',
            field=models.CharField(blank=True, default='quick', max_length=20, verbose_name='Composer Mode'),
        ),
        migrations.AddField(
            model_name='designrequest',
            name='wilaya',
            field=models.CharField(blank=True, max_length=100, verbose_name='Wilaya'),
        ),
    ]
