# Generated by Django 6.0.7 on 2026-08-22 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_designrequest_client_type_designrequest_commune_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inquiry',
        ),
        migrations.DeleteModel(
            name='Invitation',
        ),
    ]
