# Generated by Django 5.2.5 on 2026-09-04 18:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_service_enhancements_and_quotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepricing',
            name='allow_exterior',
            field=models.BooleanField(default=False, help_text='Allow this service to apply to exterior surface (e.g. 2D plans, 3D exterior)', verbose_name='Allow Exterior'),
        ),
        migrations.AddField(
            model_name='servicepricing',
            name='allow_interior',
            field=models.BooleanField(default=True, help_text='Allow this service to apply to interior surface', verbose_name='Allow Interior'),
        ),
        migrations.AddField(
            model_name='servicepricing',
            name='default_exterior_selected',
            field=models.BooleanField(default=False, verbose_name='Default Exterior Selected'),
        ),
        migrations.AddField(
            model_name='servicepricing',
            name='default_hours',
            field=models.PositiveIntegerField(default=10, verbose_name='Default Hours'),
        ),
        migrations.AddField(
            model_name='servicepricing',
            name='default_interior_selected',
            field=models.BooleanField(default=True, verbose_name='Default Interior Selected'),
        ),
        migrations.AddField(
            model_name='servicepricing',
            name='default_quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Default Quantity'),
        ),
        migrations.AddField(
            model_name='servicepricing',
            name='default_reference_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('100000.00'), max_digits=14, verbose_name='Default Reference Amount (DA)'),
        ),
        migrations.AddField(
            model_name='servicepricing',
            name='unit_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Unit Name (e.g. m², h, façade, visite, forfait)'),
        ),
    ]
