# Generated by Django 5.2.5 on 2026-09-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_servicepricing_allow_exterior_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designrequest',
            name='surface_exterior',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Surface Extérieure (m²)'),
        ),
        migrations.AddField(
            model_name='designrequest',
            name='surface_interior',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Surface Intérieure (m²)'),
        ),
        migrations.AddField(
            model_name='designrequestoption',
            name='calculation_detail',
            field=models.CharField(blank=True, max_length=255, verbose_name='Calculation Detail'),
        ),
        migrations.AddField(
            model_name='designrequestoption',
            name='hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Hours'),
        ),
        migrations.AddField(
            model_name='designrequestoption',
            name='pricing_type',
            field=models.CharField(blank=True, default='fixed', max_length=30, verbose_name='Pricing Type'),
        ),
        migrations.AddField(
            model_name='designrequestoption',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='designrequestoption',
            name='reference_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Reference Amount'),
        ),
        migrations.AddField(
            model_name='designrequestoption',
            name='use_exterior',
            field=models.BooleanField(default=False, verbose_name='Use Exterior'),
        ),
        migrations.AddField(
            model_name='designrequestoption',
            name='use_interior',
            field=models.BooleanField(default=False, verbose_name='Use Interior'),
        ),
    ]
