# Generated by Django 5.2.5 on 2026-09-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_designrequest_surface_exterior_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicepricing',
            options={'ordering': ['order', '-is_default', 'service_name'], 'verbose_name': 'Service Pricing', 'verbose_name_plural': 'Service Pricings'},
        ),
        migrations.AddField(
            model_name='servicepricing',
            name='order',
            field=models.PositiveIntegerField(blank=True, help_text='Determines the sequence in which services appear in the catalog and composer', null=True, unique=True, verbose_name='Order'),
        ),
    ]
