# Generated by Django 5.2.5 on 2026-09-04 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_alter_servicepricing_options_servicepricing_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='placement',
            field=models.CharField(choices=[('service_info', 'Service Info (.serviceInfo)'), ('info_card', 'About Info (.infoCard)'), ('videos', 'Videos Section (#videos)')], default='videos', help_text='Choose where to put the video on the homepage.', max_length=50, verbose_name='Placement'),
        ),
        migrations.AddField(
            model_name='video',
            name='role',
            field=models.CharField(choices=[('service_design', 'Design (Usage & optimisation)'), ('service_360', '360° (Visite immersive)'), ('service_vr', 'VR (Immersion à l’échelle)'), ('service_bilnov', 'Bilnov (Projet collaboratif)'), ('service_store', 'Store Bilnov (Produits · 3D · AR · budget)'), ('info_usage', 'Usage réel'), ('info_optimization', 'Optimisation'), ('info_smart_living', 'Smart living'), ('info_immersion', 'Immersion'), ('videos_rail', 'Videos Rail Item')], default='videos_rail', help_text='Specify the exact card role for this video.', max_length=50, verbose_name='Role / Target Card'),
        ),
    ]
