# Generated by Django 5.2.5 on 2026-09-04 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0042_video_placement_video_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepricing',
            name='order',
            field=models.PositiveIntegerField(blank=True, help_text='Determines the sequence in which services appear in the catalog and composer', null=True, verbose_name='Order'),
        ),
    ]
