# Generated by Django 5.2.5 on 2026-09-05 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0043_alter_servicepricing_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designrequest',
            name='surface_exterior',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Surface Extérieure (m²)'),
        ),
        migrations.AlterField(
            model_name='designrequest',
            name='surface_interior',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Surface Intérieure (m²)'),
        ),
        migrations.AlterField(
            model_name='designrequest',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='designrequest',
            name='total_surface',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Total Surface (m²)'),
        ),
        migrations.AlterField(
            model_name='designrequestfloor',
            name='surface',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Surface (m²)'),
        ),
    ]
