# Generated by Django 6.0.7 on 2026-09-05 02:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0044_alter_designrequest_surface_exterior_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='surface_exterior',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Surface Extérieure (m²)'),
        ),
        migrations.AddField(
            model_name='quote',
            name='surface_interior',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Surface Intérieure (m²)'),
        ),
    ]
