# Generated by Django 5.2.5 on 2026-09-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0045_quote_surface_exterior_quote_surface_interior'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='html_snapshot',
            field=models.TextField(blank=True, default='', help_text='Exact rendered devis + contract HTML, saved from the composer and served at the public dossier link.', verbose_name='Devis HTML Snapshot'),
        ),
    ]
