# Generated by Django 5.2.5 on 2026-09-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0046_quote_html_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='pdf_snapshot',
            field=models.FileField(blank=True, help_text='Exact unified devis + contract PDF generated by the composer, attached when this quote is sent.', null=True, upload_to='quotes/pdf-snapshots/', verbose_name='Devis PDF Snapshot'),
        ),
    ]
