# Generated by Django 5.2.5 on 2026-09-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0047_quote_pdf_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='composer_state',
            field=models.JSONField(blank=True, help_text='Reconstructible composer selection (project, surfaces, services, client) — lets a client reopen this exact project in the composer from the public dossier link.', null=True, verbose_name='Composer State Snapshot'),
        ),
    ]
